import type { Metadata } from 'next';
import { robotoFlex, sourceSerif, greatVibes } from '@/utils/customFonts';
import { Toaster } from 'react-hot-toast';
import { AuthProvider } from '@/lib/contexts/AuthContext';
import { NotificationProvider } from '@/lib/contexts/NotificationContext';
import { ActivityProvider } from '@/lib/contexts/ActivityContext';
import { CommentsProvider } from '@/lib/contexts/CommentsContext';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sl">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto+Flex:opsz,wght@8..144,400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${robotoFlex.className} ${sourceSerif.variable} ${greatVibes.variable}`}
      >
        <AuthProvider>
          <NotificationProvider>
            <ActivityProvider>
              <CommentsProvider>
                <Toaster
                  position="top-right"
                  toastOptions={{
                    style: {
                      margin: "15px",
                      background: "#828282",
                      color: "#fff",
                      fontSize: "15px",
                      width: "340px",
                    },
                    className: "text-base",
                    duration: 3000,
                  }}
                />
                {children}
              </CommentsProvider>
            </ActivityProvider>
          </NotificationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
