name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VP_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /home/jenkins/deployment/obituary-app-fe
          git pull origin main
          npm install
          npm run build
          pm2 restart obituary-fe || pm2 start "npx serve -s build" --name obituary-frontend
