name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VP_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: |
          cd /home/jenkins/deployment/obituary-app/obituary-fe
          sleep 3
          npm install
          sleep 3
          npm run build && /root/.nvm/versions/node/v21.7.3/bin/pm2 restart obituary-fe
